### ISSUE TITLE
Precompile fails under Julia 1.7.2

### ISSUE THREAD

**Issue by nbsmokee** [meggart/NetCDF.jl#159]
The package does not precompile under Julia 1.7.2, giving the following error message:
```
julia> using NetCDF
[ Info: Precompiling NetCDF [30363a11-5582-574a-97bb-aa9a979735b9]
ERROR: LoadError: InitError: could not load library "/home/smokee/.julia/artifacts/0a7f440ba143b238cc3dd0def2956d34d76755f3/lib/libnetcdf.so"
libmbedtls.so.13: cannot open shared object file: No such file or directory
```
Maybe related to #137?

**Comment by visr** [comment]
Hmm that issue is resolved. It should work fine on julia 1.7. What kind of system are you on, and what NetCDF/NetCDF_jll versions? Are you perhaps using a homebrew build of julia?

https://github.com/Alexander-Barth/NCDatasets.jl/blob/924c69c4f8388460b2289cbfc390a1e2c9cec9d8/docs/src/issues.md#using-non-official-julia-builds

https://github.com/Alexander-Barth/NCDatasets.jl/issues/153#issuecomment-1012169911

**Comment by nbsmokee** [comment]
I'm on Manjaro Linux, and I was using Julia from the official repositories. I tried with the official binaries (package `julia-bin` from AUR), and everything is working just fine. So sorry from my side, I would have assumed that the official repos would provide the official binaries.
