### ISSUE TITLE
No NetCDF errors detected with new C interface

### ISSUE THREAD

**Issue by meggart** [meggart/NetCDF.jl#31]
@visr 
I just realized that since the upgrade no errors are thrown anymore when ccalls return an error code, so far the interface relied on this to catch errors like trying to open a non-existing file. This is probably my bad for not testing if errors are thrown if a file does not exist. How complicated would it be to change the Clang wrapper so that instead of 

``` julia
function nc_open(path,mode::Integer,ncidp)
    ccall((:nc_open,libnetcdf),Cint,(Ptr{UInt8},Cint,Ptr{Cint}),path,mode,ncidp)
end
```

something like 

``` julia
function nc_open(path,mode::Integer,ncidp)
    ret = ccall((:nc_open,libnetcdf),Cint,(Ptr{UInt8},Cint,Ptr{Cint}),path,mode,ncidp)
    ret == NC_NOERR || error("NetCDF library error thrown: Error Code $ret")
end

would be generated. If it is too complicated, I would do the checks on the nc_helpers.jl side. Just let me know....
```

**Comment by visr** [comment]
Ah yes, that should still be added.
How about using the Clang.jl rewriter functionality to wrap all ccall's into a function similar to the checknull function in GDAL.jl:

https://github.com/visr/GDAL.jl/blob/fa9d8dd4a917ff0eaf6a2436ade9f4d61eef76cd/gen/rewriter.jl#L229
https://github.com/visr/GDAL.jl/blob/8d0e806b4f01de7d9d033493b51a5b7d6aa5c6c1/src/error.jl#L36

Then instead of giving users error codes, we could call nc_strerror for an error message.
http://www.unidata.ucar.edu/software/netcdf/docs/group__error.html

I could try this out this weekend if you don't beat me to it.

**Comment by meggart** [comment]
I did'nt make it today, so go ahead if you can spare some time. I won't tackle this before Tuesday. 

I have seen `nc_strerror` before, but did not really use it because I was not sure how to deal with the memory allocated by the function (it is on the the very few ones that return a pointer and it is not mentioned in the documentation who should deallocate). 

In previous versions I referred to the Dict at the beginning of netcdf_helpers.jl to give a more meaningful message. The `nc_strerror` way would of course be more consistent.
