### ISSUE TITLE
reading char-array using the low-level interface

### ISSUE THREAD

**Issue by Alexander-Barth** [meggart/NetCDF.jl#42]
I have some troubles reading a character arrays using the low-level interface. Here is what I tried:

```
using NetCDF
fname = "argo-profiles-6900659.nc";
nc = NetCDF.open(fname);
julia> temp_qc = nc["TEMP_QC"][:];
ERROR: NetCDF error code -56:
	NetCDF: Attempt to convert between text & numbers
 in check at /home/abarth/.julia/v0.5/NetCDF/src/netcdf_helpers.jl:22 [inlined]
 in nc_get_var1_uchar(::Int32, ::Int32, ::Array{UInt64,1}, ::Array{UInt8,1}) at /home/abarth/.julia/v0.5/NetCDF/src/netcdf_c.jl:789
 in nc_get_var1_x at /home/abarth/.julia/v0.5/NetCDF/src/NetCDF.jl:267 [inlined]
 in macro expansion at /home/abarth/.julia/v0.5/NetCDF/src/NetCDF.jl:231 [inlined]
 in readvar(::NetCDF.NcVar{UInt8,2,2}, ::Int64, ::Int64) at /home/abarth/.julia/v0.5/NetCDF/src/NetCDF.jl:227
 in _unsafe_getindex at ./reshapedarray.jl:128 [inlined]
 in getindex at ./reshapedarray.jl:119 [inlined]
 in macro expansion at ./multidimensional.jl:352 [inlined]
 in macro expansion at ./cartesian.jl:64 [inlined]
 in macro expansion at ./multidimensional.jl:350 [inlined]
 in _unsafe_getindex! at ./multidimensional.jl:342 [inlined]
 in macro expansion at ./multidimensional.jl:300 [inlined]
 in _unsafe_getindex(::Base.LinearSlow, ::Base.ReshapedArray{UInt8,1,NetCDF.NcVar{UInt8,2,2},Tuple{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64}}}, ::Colon) at ./multidimensional.jl:293
 in getindex(::NetCDF.NcVar{UInt8,2,2}, ::Colon) at ./abstractarray.jl:760
```

Using the `ncread` command works however fine:
```
qc = ncread(fname,"TEMP_QC");
```

Just the type is a bit surprising (`Array{UInt8,2}`). With a `convert(Array{Char,2},qc)`, one get the expected type.

Maybe this work-around is useful for other users of the package.

The NetCDF file to reproduce this issue:
http://modb.oce.ulg.ac.be/mediawiki/upload/Alex/argo-profiles-6900659.nc

I am using Julia 0.5.2, the NetCDF package 0.4.1 and the NetCDF library of version 4.1.3 on Linux.

**Comment by meggart** [comment]
Thanks for reporting, this should definiitely be fixed for the array-like interface. The main reason for the current behavior is that until NetCDF3 there was no UBYTE data type and it was very common to use NC_CHAR variables to store compressed numeric data, interpreting these as unsigned integers. 

However, as described here https://github.com/JuliaGeo/NetCDF.jl/blob/master/doc/NetCDF.md#reading-and-writing-nc_char-and-nc_string-variables we export a conversion function to transform a UInt8 matrix to a vector of Strings. 

However, this does not help your case because the data is actually encoded in chars. 
Are there suggestions how to deal with this? Should we care about legacy NetCDF3 files? The obvious fix would be to set `NC_CHAR=>Char` here https://github.com/JuliaGeo/NetCDF.jl/blob/master/src/NetCDF.jl#L29 and everything should work as expected.

**Comment by meggart** [comment]
Forget the last part of my comment. A Julia `Char` consists of 4 bytes so it does not map to `NC_Char`. 

So the basic problem is: It would be nice to have a mapping between NetCDF data types and Julia types that works both ways but there is the ambiguity that both `NC_UBYTE` and `NC_CHAR` would map to Julias `UInt8`.

**Comment by meggart** [comment]
I think this got resolved by introducing the `ASCIIChar` type and mapping NC_Char to it
