### ISSUE TITLE
Deal with *groups* in nc data

### ISSUE THREAD

**Issue by jiahe23** [meggart/NetCDF.jl#93]
Some netcdf data files have variables categorized into groups, is there a way to read such data.

For example, if there is a variable 'a' in group 'A' in 'data.nc',

in MATLAB ncread('data.nc','/A/a') reads out such variable.

in python NetCDF4.Dataset('data.nc').groups['A'].variables['a'] also works

Is there a way to read it in Julia?

**Comment by meggart** [comment]
Groups are only allowed to be used in NetCDF4 files. Since these are technically HDF5 files, I think the best option would be to try to use the HDF5.jl package currently. which supports reading from groups. 

This package currently supports the classic data model only. However, PRs towards implementing this functionality are always welcome. The respective C functions are available (see here: https://github.com/JuliaGeo/NetCDF.jl/blob/master/src/netcdf_c.jl#L228-L254), one would just have to create nice Julia wrapper functions around them.
